### ISSUE TITLE
Can I specify several scrape_uri at the same time to scrape multiple servers?

### ISSUE THREAD

**Issue by WuLeeX** [discordianfish/nginx_exporter#34]
Now I can just specify one uri by:
`./nginx_exporter -nginx.scrape_uri http://<ip>:<port>/nginx_status -telemetry.address :<metric_port>`

But in the nginx.conf, I setup several servers by:
```
server {
        listen 1234;
        ---other loacations here----
        location /nginx_status {
            stub_status on;
            access_log logs/access1.log;
        }
    }
server {
        listen 5678;
        ---other loacations here----
        location /nginx_status {
            stub_status on;
            access_log logs/access2.log;
        }
    }
```
It seemd like I have to run TWO nginx_exporter. Is there any way to scrape all metrics among different servers by just run ONE nginx_exporter? Just like:
`./nginx_exporter  -nginx.scrape_uri http://<ip>:<port>/nginx_status http://<ip1>:<port1>/nginx_status http://<ip2>:<port2>/nginx_status`

or just use a config file like:
```
# scrape.yaml
...
scrape_uri:
  - http://<ip>:<port>/nginx_status
  - http://<ip1>:<port1>/nginx_status
  - http://<ip2>:<port2>/nginx_status
...
```

**Comment by discordianfish** [comment]
I don't think this is something we should support. In general the best practice is to run one exporter per service and I feel this applies here to "per server section". Otherwise the exporter would have to add another label for the server section etc.
If you want one exporter for everything, you can consider using the vts module and vts exporter instead. Hope that makes sense!
